/**
 * CAELUS OS — Core Simulation Engine
 * Neuro-Symbolic Causal Crisis Engine
 *
 * Toolchain: C++17, Google OR-Tools (CP-SAT), Rust FFI (Shadow-Mesh)
 * Binary target: single static binary < 50 MB (no Python, no interpreter)
 */

#include <iostream>
#include <cstdint>
#include <cstring>
#include <cstdio>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>
#include <algorithm>
#include <atomic>
#include <cstdlib>      // getenv, strtoull
#include <cctype>
#include <ctime>
#include <thread>
#include <mutex>
#include <deque>
#include <condition_variable>
#include "src/intel_core.h"
#include "ws_emitter.h"
#include "det_rng.h"
#include "plugin/caelus_plugin_registry.h"
#include "causal_engine.h"
#include "scenario_pack.h"
#include "audit_log.h"

// ─── Cross-platform env-var setter (for --det-mode seed injection) ───────────
static inline void caelus_setenv(const char* name, const char* value) {
#ifdef _WIN32
    // _putenv_s updates only the CRT environment (std::getenv); the Rust
    // staticlib reads the Win32 block via GetEnvironmentVariableW and the two
    // stores are NOT synced. Without the Win32 write, det-mode's fixed
    // identity/enclave seeds never reach the Rust layer — the audit chain
    // head then varies per run on Windows (caught by the CDET CI job).
    _putenv_s(name, value);
    SetEnvironmentVariableA(name, value);
#else
    setenv(name, value, /*overwrite=*/1);
#endif
}

static bool caelus_env_enabled(const char* name) {
    const char* v = std::getenv(name);
    if (!v || !v[0]) return false;
    std::string s(v);
    const auto first = s.find_first_not_of(" \t\r\n");
    if (first == std::string::npos) return false;
    const auto last = s.find_last_not_of(" \t\r\n");
    s = s.substr(first, last - first + 1);
    std::transform(s.begin(), s.end(), s.begin(),
                   [](unsigned char c){ return static_cast<char>(std::tolower(c)); });
    return s == "1" || s == "true" || s == "yes" || s == "on";
}

// ─── Global War Room telemetry emitter ────────────────────────────────────────
// Bound to 127.0.0.1:47809 (loopback — never leaves the machine).
// emit() is thread-safe and no-ops when no client is connected.
static caelus::WsEmitter g_emitter;

// ─── Plugin Registry + engine tick counter ────────────────────────────────────
// The registry owns solver, connector, and reporter plugin slots.
// g_tick_ctr is accessible to plugins via CaelusEngineFns::current_tick().
static caelus::PluginRegistry  g_registry;
static std::atomic<uint64_t>   g_tick_ctr{0};

// Aktif senaryo kimliği — War Room canlı snapshot yayını için (REPL tick
// döngüsü scenario_id parametresi taşımadığından burada tutulur).
static std::string             g_scenario_id;

// ─── Birleşik REPL komut kuyruğu ──────────────────────────────────────────────
// İki üretici: (1) stdin okuyucu thread (terminal kullanıcısı), (2) WsEmitter
// komut sink'i (War Room tarayıcısı). Tek tüketici: ana REPL döngüsü. Motor
// yalnız ana thread'de mutasyona uğrar; her iki girdi kaynağı da komutu buraya
// koyar, motoru asla doğrudan çağırmaz.
struct CommandQueue {
    std::mutex               m;
    std::condition_variable  cv;
    std::deque<std::string>  q;
    bool                     closed = false;

    void push(std::string s) {
        {
            std::lock_guard<std::mutex> lk(m);
            q.push_back(std::move(s));
        }
        cv.notify_one();
    }
    // Bir komut için bloke olur. false → kuyruk kapandı ve boşaldı (çıkış).
    bool pop(std::string& out) {
        std::unique_lock<std::mutex> lk(m);
        cv.wait(lk, [&]{ return !q.empty() || closed; });
        if (q.empty()) return false;
        out = std::move(q.front());
        q.pop_front();
        return true;
    }
    void close() {
        {
            std::lock_guard<std::mutex> lk(m);
            closed = true;
        }
        cv.notify_all();
    }
};
static CommandQueue g_repl_cmds;

// ─── Denetim Günlüğü (R6) ────────────────────────────────────────────────────
// Blake3-zincirli, ed25519-mühürlü, append-only adli kayıt.
// Her oturum: caelus_audit_<session_id_hex>.log dosyasına yazılır.
static caelus::AuditLog g_audit;

// ─── Embedded UI Payload (generated by build.bat / build.sh Phase 1) ─────────
// When CAELUS_EMBEDDED_UI is defined the entire Strategic Room interface
// (index.html + scenario_compiler.js + app.js) lives inside this header as
// static byte arrays.
#ifdef CAELUS_EMBEDDED_UI
#  include "ui_payload.h"

/// Extract embedded UI to a temp path so a local browser can open it.
/// The files are DELETED on process exit (see cleanup in main) so no cleartext
/// UI persists after the session — matching the air-gapped claim.
static bool DumpEmbeddedUI(const std::string& html_path,
                           const std::string& compiler_path,
                           const std::string& js_path) {
    auto write_bytes = [](const std::string& path,
                          const unsigned char* data, std::size_t len) -> bool {
        FILE* f = std::fopen(path.c_str(), "wb");
        if (!f) return false;
        std::fwrite(data, 1, len, f);
        std::fclose(f);
        return true;
    };
    bool ok = true;
    ok &= write_bytes(html_path, CAELUS_UI_HTML, CAELUS_UI_HTML_LEN);
    ok &= write_bytes(compiler_path, CAELUS_SCENARIO_COMPILER_JS,
                      CAELUS_SCENARIO_COMPILER_JS_LEN);
    ok &= write_bytes(js_path,   CAELUS_UI_JS,   CAELUS_UI_JS_LEN);
    return ok;
}
#endif // CAELUS_EMBEDDED_UI

// ─── Google OR-Tools — now handled inside caelus_solver.h (ORToolsSolver) ─────
// The CAELUS_WITH_ORTOOLS flag still controls linking; the solver plugin layer
// in caelus_solver.h includes the OR-Tools header when the flag is set and
// transparently falls back to DeterministicSolver when it is not.

// ─── Rust Shadow-Mesh FFI declarations ────────────────────────────────────────
// These symbols are resolved at link time from the Rust staticlib.
extern "C" {
    // Opaque handle to a Rust-managed device identity (ed25519 keypair).
    struct CaelusIdentityHandle;

    /// Allocate an ephemeral device identity (generates ed25519 keypair).
    CaelusIdentityHandle* caelus_identity_new();

    /// Load (or create + persist) a device identity from a UTF-8 path. The path
    /// is a (ptr,len) pair (not assumed NUL-terminated). Returns NULL on error.
    CaelusIdentityHandle* caelus_identity_load_or_create(const uint8_t* path, size_t path_len);

    /// Release a Rust-heap identity. Passing NULL is safe (no-op).
    void caelus_identity_free(CaelusIdentityHandle* handle);

    /// Copy the 32-byte Blake3 fingerprint into out_fp. Returns 1 on success.
    uint8_t caelus_identity_fingerprint(const CaelusIdentityHandle* handle, uint8_t* out_fp);

    /// Copy the 32-byte ed25519 verifying key into out_vk. Returns 1 on success.
    uint8_t caelus_identity_pubkey(const CaelusIdentityHandle* handle, uint8_t* out_vk);

    /// Result of a full Shadow-Mesh handshake.
    struct CaelusSessionResult {
        bool     success;
        uint64_t session_id;
        uint8_t  shared_key[32];
        uint8_t  peer_fingerprint[32];
        bool     slot_verified;
        uint8_t  error_msg[128];
    };

    /// Full in-process CAELUS mesh handshake (loopback simulation / integration test).
    CaelusSessionResult caelus_mesh_handshake(
        const CaelusIdentityHandle* initiator, uint64_t initiator_slot_id,
        const CaelusIdentityHandle* responder, uint64_t responder_slot_id);

    // ── Discovery + Intel Feed context ────────────────────────────────────────
    struct CaelusDiscoveryCtx;

    /// A field intelligence report (repr(C) — matches the Rust IntelFeedPacket).
    struct IntelFeedPacket {
        uint64_t session_id;
        uint8_t  source_fingerprint[32];
        uint32_t friction_coefficient_fp;  // friction * 1_000_000, clamped to ≤1_000_000
        uint8_t  crisis_level;             // 0=NOMINAL 1=ELEVATED 2=HIGH 3=CRITICAL (clamped)
        uint8_t  memo[128];                // bounded, NUL-padded
        uint64_t observed_at;
    };

    /// Allocate a discovery + intel context bound to the local device identity.
    CaelusDiscoveryCtx* caelus_discovery_new(const CaelusIdentityHandle* identity,
                                             uint64_t local_slot_id);

    /// Start / stop the real UDP multicast discovery loops. Return 1 on success.
    uint8_t caelus_discovery_start(CaelusDiscoveryCtx* ctx);
    uint8_t caelus_discovery_stop(CaelusDiscoveryCtx* ctx);

    /// Free the discovery context (stops loops first). NULL is a safe no-op.
    void caelus_discovery_free(CaelusDiscoveryCtx* ctx);

    /// Fetch up to max_peers fingerprints (32 bytes each) from the peer table.
    size_t caelus_fetch_nearby_peers(const CaelusDiscoveryCtx* ctx,
                                     uint8_t* out_fingerprints, size_t max_peers);

    /// Inject a field intel packet. `memo`/`memo_len` is a bounded buffer.
    /// Returns 1 on success, 0 on error.
    uint8_t caelus_inject_intel_packet(
        CaelusDiscoveryCtx* ctx, uint64_t session_id, const uint8_t* source_fp,
        uint32_t friction_fp, uint8_t crisis_level, const uint8_t* memo, size_t memo_len);

    /// Drain the next IntelFeedPacket. Returns 1 if written, 0 if empty.
    uint8_t caelus_fetch_intel_feed(CaelusDiscoveryCtx* ctx, IntelFeedPacket* out_pkt);

    // ── Virtual clock control (discovery.rs — deterministic CI testing) ───────
    /// Freeze the Rust discovery clock at tick_secs (0 = UNIX epoch).
    /// All beacon timestamps, TTLs and freshness checks use this fixed value.
    void caelus_clock_set_virtual(uint64_t tick_secs);
    /// Restore the real wall-clock after a deterministic test run.
    void caelus_clock_use_real();

    // ── KEYMGMT delege kaydı (mesh_auth.rs — T-23 KEYMGMT-WIRE) ───────────────
    /// Rust kimlik katmanına KEYMGMT delegesi kaydeder/temizler.
    /// İki callback de non-NULL → kayıt (kimlik koruması plugin'e delege edilir);
    /// ikisi de NULL → temizleme (DPAPI/env fallback'e dönüş); tek NULL → ret.
    /// CaelusKeyBlob, caelus_plugin_abi.h'deki tanımla bit-bit aynıdır
    /// (Rust tarafında repr(C) aynası). Dönüş: 1 başarı, 0 ret.
    uint8_t caelus_keymgmt_register(
        uint8_t (*protect_fn)(void*, const CaelusKeyBlob*, CaelusKeyBlob*),
        uint8_t (*unprotect_fn)(void*, const CaelusKeyBlob*, CaelusKeyBlob*),
        void* state);
}

// ─── Utility: hex-encode a byte buffer ────────────────────────────────────────
static std::string hex_encode(const uint8_t* buf, size_t len) {
    std::ostringstream oss;
    oss << std::hex << std::setfill('0');
    for (size_t i = 0; i < len; ++i)
        oss << std::setw(2) << static_cast<unsigned>(buf[i]);
    return oss.str();
}

// ─── T-18 Üretim Plugin İmza Verifier'ı (pinli güven çapası) ──────────────────
// Üretim güven çapası: tools/caelus_trusted_pubkey.txt içeriğiyle aynı ed25519
// pubkey (repo DIŞINDA/offline tutulan signing seed'in public yarısı; anahtar
// töreni çıktısı). Dinamik eklenti sidecar imzaları (<plugin>.sig) YALNIZ bu anahtarla
// kabul edilir — imza string'ine gömülü rastgele bir pubkey'in matematiksel
// olarak doğrulanması yeterli DEĞİLDİR (E-3 gömülü-anahtara-güven açığının
// plugin hattında tekrarlanmaması için).
//
// TEKNİK BORÇ (bilinçli çift sabit): scenario_pack.h'ye paralel ajan, senaryo
// hattı için benzer bir pinli sabit (CAELUS_TRUSTED_PUBKEY) ekliyor. Aynı
// anahtarın iki kopyası iki ayrı dosyada yaşıyor; ileride ikisi tek bir
// "güven çapası" modülünde (örn. include/trust_anchor.h) birleştirilmeli.
// scenario_pack.h şu an aktif düzenlendiği için burada kasıtlı olarak ayrı
// ve farklı isimli bir sabit tanımlandı.
static constexpr uint8_t CAELUS_TRUSTED_PLUGIN_PUBKEY[32] = {
    0xa1, 0x1b, 0x52, 0x8e, 0x53, 0x44, 0xd9, 0xaa,
    0x71, 0x47, 0x47, 0x3b, 0xf1, 0x6c, 0xe9, 0xe9,
    0xc9, 0x77, 0xf8, 0x96, 0x08, 0x95, 0x8b, 0x58,
    0x63, 0x59, 0x41, 0x4c, 0xc7, 0xe9, 0x7e, 0x7f,
};

/// DynamicPluginLoader::CaelusPluginSignatureVerifier imzasına uygun üretim
/// verifier'ı. Adımlar (hepsi geçmek zorunda — aksi hâlde strict-fail reddi):
///   1. "<plugin>.sig" sidecar'ını oku, 2. "ed25519:<pub>:<sig>" parse et,
///   3. pubkey'i CAELUS_TRUSTED_PLUGIN_PUBKEY piniyle karşılaştır,
///   4. plugin'in ham byte'larını oku, 5. "CAELUS_PLUGIN_V1\n"||bytes mesajını
///   caelus_verify_scenario_signature FFI'siyle ed25519 doğrula.
static bool VerifyPluginSignatureProd(const char* path, void* /*user_ctx*/) noexcept {
    return caelus::verify_plugin_sidecar_ed25519(path, CAELUS_TRUSTED_PLUGIN_PUBKEY);
}

struct ConnectorIntelBridge {
    caelus::causal::CausalEngine* causal = nullptr;
};

static uint8_t InjectConnectorIntel(void* ctx, double friction_coeff,
                                    uint8_t crisis_level,
                                    const char* memo, size_t memo_len) noexcept {
    auto* bridge = static_cast<ConnectorIntelBridge*>(ctx);
    if (!bridge || !bridge->causal) return 0;

    char memo_buf[128] = {};
    if (memo && memo_len > 0) {
        const size_t n = std::min(memo_len, sizeof(memo_buf) - 1);
        std::memcpy(memo_buf, memo, n);
        memo_buf[n] = '\0';
    }

    bridge->causal->inject_intel(
        std::clamp(friction_coeff, 0.0, 1.0),
        static_cast<int>(std::min<uint8_t>(crisis_level, 3)),
        memo_buf);
    return 1;
}

// ─── Shadow-Mesh Handshake (loopback integration check) ───────────────────────
static void RunShadowMeshHandshake() {
    std::cout << "\n[MESH] -- Shadow-Mesh P2P Handshake (loopback test) ------\n";

    CaelusIdentityHandle* actor_a_id = caelus_identity_new();
    if (!actor_a_id) {
        std::cerr << "[MESH] FATAL: could not allocate Actor_Alpha identity\n";
        return;
    }
    uint8_t actor_a_fp[32] = {};
    caelus_identity_fingerprint(actor_a_id, actor_a_fp);
    std::cout << "[MESH] Actor_Alpha fingerprint : " << hex_encode(actor_a_fp, 16) << "...\n";

    CaelusIdentityHandle* actor_b_id = caelus_identity_new();
    if (!actor_b_id) {
        std::cerr << "[MESH] FATAL: could not allocate Actor_Beta identity\n";
        caelus_identity_free(actor_a_id);
        return;
    }
    uint8_t actor_b_fp[32] = {};
    caelus_identity_fingerprint(actor_b_id, actor_b_fp);
    std::cout << "[MESH] Actor_Beta fingerprint : " << hex_encode(actor_b_fp, 16) << "...\n";

    // OTP slot IDs (from the pre-distributed air-gapped slot manifest).
    constexpr uint64_t ACTOR_ALPHA_SLOT = 0x202606070001ULL;
    constexpr uint64_t ACTOR_BETA_SLOT  = 0x202606070000ULL;

    CaelusSessionResult result = caelus_mesh_handshake(
        actor_a_id, ACTOR_ALPHA_SLOT, actor_b_id, ACTOR_BETA_SLOT);

    if (result.success && result.slot_verified) {
        std::cout << "[MESH] Handshake SUCCESS (slot verified)\n";
        std::cout << "       Session ID      : 0x" << std::hex << result.session_id << std::dec << "\n";
        std::cout << "       Shared Key      : " << hex_encode(result.shared_key, 16) << "...\n";
        std::cout << "       Peer Fingerprint: " << hex_encode(result.peer_fingerprint, 16) << "...\n";
        std::string hs_json = caelus::ws_json::handshake_event(
            hex_encode(result.peer_fingerprint, 32), result.session_id, true);
        g_emitter.emit(hs_json);
        g_audit.append(hs_json);
    } else {
        // Authorization is enforced now: success requires a verified slot claim.
        const char* msg = reinterpret_cast<const char*>(result.error_msg);
        std::cout << "[MESH] Handshake REJECTED: "
                  << (msg[0] ? msg : "slot not verified") << "\n";
        std::string hs_fail = caelus::ws_json::handshake_event("", 0, false);
        g_emitter.emit(hs_fail);
        g_audit.append(hs_fail);
    }

    caelus_identity_free(actor_a_id);
    caelus_identity_free(actor_b_id);
    std::cout << "[MESH] Identities released.\n";
}

// ─── Solver Plugin Dispatch  ──────────────────────────────────────────────────
/**
 * RunOptimizationCycle
 *
 * Dispatches to the active solver plugin via g_registry.solve().
 * The solver (DeterministicSolver or ORToolsSolver) is selected at bootstrap
 * and hidden behind the plugin ABI — this function contains no solver logic.
 *
 * Adding a new solver:
 *   1. Implement struct MySolver : SolverBase<MySolver> { ... };
 *   2. Call g_registry.set_solver(MySolver::make_vtable()) in main().
 *   Done — this function needs no changes.
 */
static caelus::SolverResult RunOptimizationCycle(double friction_multiplier) {
    using caelus::intel::FRICTION_MULTIPLIER_MAX;
    using caelus::intel::FRICTION_MULTIPLIER_MIN;

    // Defense in depth: clamp before handing to the plugin.
    friction_multiplier = std::clamp(friction_multiplier,
                                     FRICTION_MULTIPLIER_MIN, FRICTION_MULTIPLIER_MAX);

    // Emit the friction to the War Room before solving.
    g_emitter.emit(caelus::ws_json::friction(friction_multiplier, 0, 0));

    // Build the solver request (domain-agnostic timing constants).
    caelus::SolverRequest req;
    req.friction_multiplier   = friction_multiplier;
    req.task_start_min        = 360;  // 06:00
    req.target_deadline_min   = 480;  // 08:00
    req.commit_overhead_min   = 30;
    req.base_transit_low_min  = 45;
    req.base_transit_high_min = 65;

    std::cout << "\n[CORE] -- Solver Plugin [" << g_registry.solver_name()
              << "] ----------------\n";
    std::cout << "[CORE] Cycle: Generic constrained transfer\n";
    std::cout << "[CORE] Task starts 06:00 | Deadline 08:00\n";
    std::cout << "[CORE] Friction multiplier: " << std::fixed << std::setprecision(2)
              << friction_multiplier << "x  → travel band ["
              << req.travel_low() << ", " << req.travel_high() << "] min\n\n";

    // ── Plugin dispatch ─────────────────────────────────────────────────────
    // g_registry.solve() selects ORToolsSolver (minimise) or DeterministicSolver
    // (worst-case band) depending on what was registered at bootstrap.
    // If the registered solver fails, it silently falls back to Deterministic.
    caelus::SolverResult res = g_registry.solve(req);

    // ── Print result ────────────────────────────────────────────────────────
    auto fmt = [](int m) -> std::string {
        char b[8];
        std::snprintf(b, sizeof(b), "%d:%02d", m / 60, m % 60);
        return b;
    };
    if (res.feasible) {
        std::cout << "[CORE] Solver: " << (res.on_time ? "ON TIME" : "AT RISK") << "\n";
        std::cout << "       Arrival time     : " << fmt(res.arrival) << "\n";
        std::cout << "       Completion time  : " << fmt(res.completion) << "\n";
        std::cout << "       OTP Status       : "
                  << (res.on_time ? "ON TIME" : "AT RISK / DELAYED") << "\n";
    } else {
        std::cout << "[CORE] Solver: No feasible solution — OTP AT RISK\n";
    }
    std::cout << "[CORE] ---------------------------------------------------\n";

    g_emitter.emit(caelus::ws_json::optimization_result(
        res.on_time, res.arrival, res.completion, friction_multiplier));

    return res;
}

// ─── FieldMultiplierFromPacket — KALDIRILDI (Causal Engine v2 ile değiştirildi) ──
// Eski formül: m = 1.0 + field_coeff + crisis_level * 0.25
// Yeni yol:    caelus::causal::CausalEngine::inject_intel(coeff, level, memo)
//              Graf düğümlerini günceller; aggregate_friction() sonucu verir.
// Bu fonksiyon artık çağrılmıyor; referans için tutulmuyor.

// ─── Senaryo REPL (R9) ───────────────────────────────────────────────────────
static std::string trim_copy(const std::string& s) {
    const auto first = s.find_first_not_of(" \t\r\n");
    if (first == std::string::npos) return {};
    const auto last = s.find_last_not_of(" \t\r\n");
    return s.substr(first, last - first + 1);
}

static std::string json_escape(const std::string& s) {
    std::string out;
    out.reserve(s.size() + 8);
    for (char c : s) {
        switch (c) {
            case '\\': out += "\\\\"; break;
            case '"':  out += "\\\""; break;
            case '\n': out += "\\n";  break;
            case '\r': out += "\\r";  break;
            case '\t': out += "\\t";  break;
            default:   out += c;      break;
        }
    }
    return out;
}

static bool g_json_stdout = false;

static void audit_repl_event(const std::string& command,
                             const caelus::causal::CausalEngine& engine,
                             const char* result) {
    if (!g_audit.is_open()) return;
    std::ostringstream ss;
    ss << "{\"type\":\"REPL_COMMAND\","
       << "\"command\":\"" << json_escape(command) << "\","
       << "\"tick\":" << engine.current_tick() << ","
       << "\"friction\":" << std::fixed << std::setprecision(6)
       << engine.friction_multiplier() << ","
       << "\"regime_exceeded\":" << (engine.regime_exceeded() ? "true" : "false") << ","
       << "\"outage\":" << (engine.outage_active() ? "true" : "false") << ","
       << "\"result\":\"" << result << "\"}";
    g_audit.append(ss.str());
}

// Intel veri düzlemi retlerini (imza/token kapısı, okuyucu thread'lerdeki
// atomik sayaç) motor thread'inde adli zincire işler; her
// dispatch_connectors() geçişinden sonra çağrılır. Audit henüz açık değilse
// delta birikir ve açıldığında tek olayda raporlanır.
static void audit_intel_rejections() {
    static uint64_t last_seen = 0;
    const uint64_t total = caelus::connector_detail::intel_rejected_total()
                               .load(std::memory_order_relaxed);
    if (total == last_seen || !g_audit.is_open()) return;
    std::ostringstream ss;
    ss << "{\"type\":\"INTEL_REJECTED\",\"delta\":" << (total - last_seen)
       << ",\"total\":" << total << "}";
    g_audit.append(ss.str());
    last_seen = total;
}

// NodeKind → War Room etiketi (UI causal graph düğüm tipleri).
static const char* node_kind_label(caelus::causal::NodeKind k) noexcept {
    switch (k) {
        case caelus::causal::NodeKind::Service:    return "Service";
        case caelus::causal::NodeKind::Buffer:     return "Buffer";
        case caelus::causal::NodeKind::Queue:      return "Queue";
        case caelus::causal::NodeKind::Perishable: return "Perishable";
        case caelus::causal::NodeKind::Gate:       return "Gate";
        case caelus::causal::NodeKind::Adversary:  return "Adversary";
    }
    return "Service";
}

// Motorun GERÇEK graf durumunu War Room'a yayınlar (UI'ın `snapshot` olayı:
// causal graph + düğüm sinyalleri + analiz paneli bundan beslenir). Demo/sahte
// veri değildir — doğrudan CausalEngine'in canlı düğüm/kenar vektörlerinden
// serileştirilir.
static void emit_ws_snapshot(const caelus::causal::CausalEngine& engine,
                             const std::string& scenario_id) {
    using caelus::causal::fp_to_d;
    std::ostringstream o;
    o << std::fixed << std::setprecision(6);
    o << "{\"type\":\"snapshot\","
      << "\"scenario_id\":\"" << json_escape(scenario_id) << "\","
      << "\"tick\":" << engine.current_tick() << ","
      << "\"clamped_friction\":" << engine.friction_multiplier() << ","
      << "\"regime_exceeded\":" << (engine.regime_exceeded() ? "true" : "false") << ","
      << "\"outage_active\":" << (engine.outage_active() ? "true" : "false") << ","
      << "\"nodes\":[";
    bool first = true;
    for (const auto& n : engine.nodes()) {
        if (!first) o << ",";
        first = false;
        o << "{\"id\":\"" << json_escape(n.id) << "\","
          << "\"type\":\"" << node_kind_label(n.kind) << "\","
          << "\"state\":" << fp_to_d(n.state_fp) << ","
          << "\"reported\":" << fp_to_d(n.reported_state_fp) << ","
          << "\"trust\":" << fp_to_d(n.trust_fp) << ","
          << "\"friction\":" << fp_to_d(n.weight_fp) << ","
          << "\"capacity\":" << fp_to_d(n.capacity_fp) << ","
          << "\"irrecoverable\":" << (n.irrecoverable ? "true" : "false") << "}";
    }
    o << "],\"edges\":[";
    first = true;
    for (const auto& e : engine.edges()) {
        if (e.to.empty()) continue;  // sürtünme-toplama kenarı (görselleştirilmez)
        if (!first) o << ",";
        first = false;
        o << "{\"from\":\"" << json_escape(e.from) << "\","
          << "\"to\":\"" << json_escape(e.to) << "\","
          << "\"weight\":" << fp_to_d(e.multiplier_fp) << ","
          << "\"lag_ticks\":" << e.lag_ticks << "}";
    }
    o << "]}";
    g_emitter.emit(o.str());
}

static const caelus::causal::Lever* find_pack_lever(const caelus::ScenarioPack& pack,
                                                    const std::string& id) {
    for (const auto& lever : pack.levers)
        if (lever.id == id) return &lever;
    return nullptr;
}

static void print_repl_help() {
    std::cout
        << "\n[REPL] Komutlar:\n"
        << "  status | snapshot       Guncel tick, surtunme ve rejim durumunu yazdir\n"
        << "  status --json           Makine-okunur deterministik snapshot yazdir\n"
        << "  snapshot --json         Makine-okunur deterministik snapshot yazdir\n"
        << "  tick <sayi>             Motoru N tick ilerlet; zamanli intel olaylarini uygula\n"
        << "  lever <id>              Senaryo kaldiracini uygula ve 1 tick yay\n"
        << "  list levers             Yuklu senaryo kaldiraclarini listele\n"
        << "  help                    Bu yardimi yazdir\n"
        << "  quit | exit             REPL'den cik\n";
}

static void print_repl_snapshot(const caelus::causal::CausalEngine& engine,
                                const caelus::causal::EngineSnapshot& snap) {
    std::cout << std::fixed << std::setprecision(6);
    std::cout << "[REPL] Snapshot:\n"
              << "       current_tick      : " << engine.current_tick() << "\n"
              << "       last_snapshot_tick: " << snap.tick << "\n"
              << "       raw_friction     : " << snap.raw_friction_d() << "x\n"
              << "       clamped_friction : " << snap.clamped_friction_d() << "x\n"
              << "       live_multiplier  : " << engine.friction_multiplier() << "x\n"
              << "       regime_exceeded  : " << (engine.regime_exceeded() ? "EVET" : "HAYIR") << "\n"
              << "       outage_active    : " << (engine.outage_active() ? "EVET" : "HAYIR") << "\n"
              << "       deadline_missed  : " << (snap.any_deadline_missed ? "EVET" : "HAYIR") << "\n"
              << "       hysteresis_flip  : " << (snap.any_hysteresis_flip ? "EVET" : "HAYIR") << "\n"
              << "       throughput_ratio : " << snap.throughput_ratio << "\n"
              << "       summary          : " << snap.summary << "\n";
}

static void print_repl_snapshot_json(const std::string& scenario_id,
                                     const caelus::causal::CausalEngine& engine,
                                     const caelus::causal::EngineSnapshot& snap) {
    std::cout << std::fixed << std::setprecision(6);
    if (!g_json_stdout) std::cout << "[REPL_JSON] ";
    std::cout << "{"
              << "\"type\":\"snapshot\","
              << "\"scenario_id\":\"" << json_escape(scenario_id) << "\","
              << "\"current_tick\":" << engine.current_tick() << ","
              << "\"last_snapshot_tick\":" << snap.tick << ","
              << "\"raw_friction\":" << snap.raw_friction_d() << ","
              << "\"clamped_friction\":" << snap.clamped_friction_d() << ","
              << "\"live_multiplier\":" << engine.friction_multiplier() << ","
              << "\"regime_exceeded\":" << (engine.regime_exceeded() ? "true" : "false") << ","
              << "\"outage_active\":" << (engine.outage_active() ? "true" : "false") << ","
              << "\"deadline_missed\":" << (snap.any_deadline_missed ? "true" : "false") << ","
              << "\"hysteresis_flip\":" << (snap.any_hysteresis_flip ? "true" : "false") << ","
              << "\"throughput_ratio_fp\":" << snap.throughput_ratio_fp << ","
              << "\"throughput_ratio\":" << snap.throughput_ratio << ","
              << "\"summary\":\"" << json_escape(snap.summary) << "\""
              << "}\n";
}

static void print_repl_levers(const caelus::ScenarioPack& pack, bool pack_loaded) {
    if (!pack_loaded || pack.levers.empty()) {
        std::cout << "[REPL] Yuklu senaryo kaldiraci yok.\n";
        return;
    }
    std::cout << "[REPL] Kaldiraclar:\n";
    for (const auto& lever : pack.levers) {
        std::cout << "  " << lever.id
                  << "  target=" << lever.target
                  << "  p=" << std::fixed << std::setprecision(2)
                  << caelus::causal::fp_to_d(lever.success_p_fp)
                  << "  cost_ticks=" << lever.cost_ticks
                  << "  lockout_ticks=" << lever.lockout_ticks << "\n";
    }
}

static caelus::causal::EngineSnapshot run_repl_tick(
    caelus::causal::CausalEngine& engine) {
    const uint64_t tick_before = engine.current_tick();
    g_tick_ctr.store(tick_before, std::memory_order_relaxed);
    const size_t delivered = g_registry.dispatch_connectors();
    if (delivered > 0) {
        std::cout << "[CONNECTOR] Tick " << tick_before << ": "
                  << delivered << " intel olayi enjekte edildi.\n";
    }
    audit_intel_rejections();

    caelus::causal::EngineSnapshot snap = engine.run_ticks(1);
    g_emitter.emit(caelus::ws_json::friction(
        snap.clamped_friction_d(),
        snap.outage_active ? 3 : (snap.regime_exceeded ? 2 : 0),
        engine.current_tick()));

    if (g_audit.is_open()) {
        std::ostringstream ss;
        ss << std::fixed << std::setprecision(6);
        ss << "{\"type\":\"REPL_TICK\","
           << "\"tick_before\":" << tick_before
           << ",\"tick_after\":" << engine.current_tick()
           << ",\"raw_friction\":" << snap.raw_friction_d()
           << ",\"clamped_friction\":" << snap.clamped_friction_d()
           << ",\"regime_exceeded\":" << (snap.regime_exceeded ? "true" : "false")
           << ",\"outage\":" << (snap.outage_active ? "true" : "false")
           << ",\"deadline_missed\":" << (snap.any_deadline_missed ? "true" : "false")
           << ",\"hysteresis_flip\":" << (snap.any_hysteresis_flip ? "true" : "false")
           << "}";
        g_audit.append(ss.str());
    }

    // War Room canlı yayını: throughput göstergesi + gerçek graf snapshot'ı.
    // Yalnız bir tarayıcı bağlıyken serileştirme maliyetine gireriz.
    if (g_emitter.connected()) {
        g_emitter.emit(caelus::ws_json::engine_state(
            g_scenario_id.empty() ? "LIVE" : g_scenario_id, g_scenario_id,
            engine.current_tick(), snap.clamped_friction_d(),
            snap.throughput_ratio, snap.outage_active, snap.any_hysteresis_flip));
        emit_ws_snapshot(engine, g_scenario_id);
    }

    return snap;
}

static caelus::causal::EngineSnapshot RunScenarioRepl(
    caelus::causal::CausalEngine& engine,
    const caelus::ScenarioPack& pack,
    bool pack_loaded,
    const std::string& scenario_id,
    caelus::causal::EngineSnapshot last_snap) {
    std::cout << "\n[REPL] Senaryo REPL basladi. Yardim icin 'help', cikis icin 'quit'.\n";
    print_repl_snapshot(engine, last_snap);

    // War Room tarayıcısından gelen komutları (WS text frame) da bu REPL'e
    // yönlendir: gerçek motor sürülür, snapshot geri yayınlanır. Handler
    // emitter thread'inde koşar, sadece kuyruğa iter (motora dokunmaz).
    g_emitter.on_command([](std::string c){ g_repl_cmds.push(std::move(c)); });

    // stdin ayrı bir thread'de okunup aynı kuyruğa beslenir; ana döngü tek
    // tüketici olarak terminal + tarayıcı komutlarını sırayla işler.
    std::thread stdin_thread([]{
        std::string in;
        while (std::getline(std::cin, in)) g_repl_cmds.push(in);
        g_repl_cmds.close();
    });
    stdin_thread.detach();

    std::string line;
    while (true) {
        std::cout << "\ncaelus:" << scenario_id << " t=" << engine.current_tick() << "> ";
        if (!g_repl_cmds.pop(line)) {
            std::cout << "\n[REPL] stdin kapandi, cikiliyor.\n";
            break;
        }

        const std::string command_line = trim_copy(line);
        if (command_line.empty()) continue;

        std::istringstream iss(command_line);
        std::string cmd;
        iss >> cmd;
        std::transform(cmd.begin(), cmd.end(), cmd.begin(),
                       [](unsigned char c){ return static_cast<char>(std::tolower(c)); });

        if (cmd == "quit" || cmd == "exit") {
            audit_repl_event(command_line, engine, "quit");
            std::cout << "[REPL] Cikis.\n";
            break;
        }
        if (cmd == "help" || cmd == "?") {
            print_repl_help();
            audit_repl_event(command_line, engine, "ok");
            continue;
        }
        if (cmd == "status" || cmd == "snapshot") {
            std::string format;
            iss >> format;
            std::transform(format.begin(), format.end(), format.begin(),
                           [](unsigned char c){ return static_cast<char>(std::tolower(c)); });
            if (format == "--json" || format == "json") {
                print_repl_snapshot_json(scenario_id, engine, last_snap);
            } else {
                print_repl_snapshot(engine, last_snap);
            }
            // War Room "ANALİZ ET" bu komutu gönderir: gerçek graf snapshot'ını
            // WS üzerinden geri yayınla (analiz paneli motorun canlı verisiyle dolar).
            if (g_emitter.connected()) emit_ws_snapshot(engine, g_scenario_id);
            audit_repl_event(command_line, engine, "ok");
            continue;
        }
        if (cmd == "list") {
            std::string what;
            iss >> what;
            std::transform(what.begin(), what.end(), what.begin(),
                           [](unsigned char c){ return static_cast<char>(std::tolower(c)); });
            if (what == "levers") {
                print_repl_levers(pack, pack_loaded);
                // War Room lever konsolu: gerçek kaldıraç listesini WS'e yayınla
                // (UI'daki hardcoded ipuçları yerine motorun paketinden gelir).
                if (g_emitter.connected()) {
                    std::ostringstream lo;
                    lo << "{\"type\":\"levers\",\"scenario_id\":\""
                       << json_escape(g_scenario_id) << "\",\"levers\":[";
                    bool lf = true;
                    if (pack_loaded) {
                        for (const auto& lv : pack.levers) {
                            if (!lf) lo << ",";
                            lf = false;
                            lo << "{\"id\":\"" << json_escape(lv.id) << "\","
                               << "\"target\":\"" << json_escape(lv.target) << "\","
                               << "\"success_p\":" << std::fixed << std::setprecision(2)
                               << caelus::causal::fp_to_d(lv.success_p_fp) << ","
                               << "\"cost_ticks\":" << lv.cost_ticks << ","
                               << "\"lockout_ticks\":" << lv.lockout_ticks << "}";
                        }
                    }
                    lo << "]}";
                    g_emitter.emit(lo.str());
                }
                audit_repl_event(command_line, engine, "ok");
            } else {
                std::cout << "[REPL] Bilinmeyen liste. Ornek: list levers\n";
                audit_repl_event(command_line, engine, "error");
            }
            continue;
        }
        if (cmd == "tick") {
            uint64_t n = 1;
            if (iss >> n) {
                if (n == 0 || n > 100000) {
                    std::cout << "[REPL] tick sayisi 1..100000 araliginda olmali.\n";
                    audit_repl_event(command_line, engine, "error");
                    continue;
                }
            }

            for (uint64_t i = 0; i < n; ++i) {
                last_snap = run_repl_tick(engine);
            }
            std::cout << "[REPL] " << n << " tick tamamlandi.\n";
            print_repl_snapshot(engine, last_snap);
            audit_repl_event(command_line, engine, "ok");
            continue;
        }
        if (cmd == "lever") {
            std::string lever_id;
            iss >> lever_id;
            if (lever_id.empty()) {
                std::cout << "[REPL] Kullanim: lever <id>\n";
                audit_repl_event(command_line, engine, "error");
                continue;
            }
            const caelus::causal::Lever* meta =
                pack_loaded ? find_pack_lever(pack, lever_id) : nullptr;
            if (!meta) {
                std::cout << "[REPL] Kaldirac bulunamadi: " << lever_id
                          << " (liste icin: list levers)\n";
                audit_repl_event(command_line, engine, "error");
                continue;
            }

            const bool success = engine.apply_lever(lever_id);
            const int remaining_cost =
                meta->cost_ticks > 1 ? (meta->cost_ticks - 1) : 0;
            std::cout << "[REPL] Lever sonucu: " << (success ? "BASARILI" : "BASARISIZ/KILITLI")
                      << " | cost_ticks=" << meta->cost_ticks
                      << " (tam maliyet icin ek tick: " << remaining_cost << ")\n";
            last_snap = run_repl_tick(engine);
            print_repl_snapshot(engine, last_snap);
            audit_repl_event(command_line, engine, success ? "success" : "failed_or_locked");
            continue;
        }

        std::cout << "[REPL] Bilinmeyen komut: " << cmd << " (yardim: help)\n";
        audit_repl_event(command_line, engine, "error");
    }

    return last_snap;
}

static int PrintScenarioCanonicalPayload(const std::string& path) {
    std::string payload;
    std::string error;
    if (!caelus::ScenarioPack::canonical_signed_payload_from_file(path, payload, &error)) {
        std::cerr << "[SIGNER] Canonical payload üretilemedi: " << error << "\n";
        return 2;
    }
    std::cout << payload;
    return 0;
}

static int ReportScenarioSignerBlocked(const std::string& path,
                                       const std::string& key_path) {
    (void)key_path;
    std::string payload;
    std::string error;
    if (!caelus::ScenarioPack::canonical_signed_payload_from_file(path, payload, &error)) {
        std::cerr << "[SIGNER] Imzalanacak payload üretilemedi: " << error << "\n";
        return 2;
    }
    std::cerr
        << "[SIGNER] BLOCKER: Bu binary içinde export edilmiş ed25519 signing FFI sembolü yok.\n"
        << "         Mevcut Rust FFI yalnız doğrulama sağlıyor "
        << "(caelus_verify_scenario_signature); C++ tarafında seed ile imza atacak\n"
        << "         hazır fonksiyon bulunmadığı için iki dosya sınırında gerçek imza üretilemiyor.\n"
        << "         Payload almak için: --print-scenario-payload <json>\n";
    return 3;
}

// ─── Entry Point ──────────────────────────────────────────────────────────────
int main(int argc, char* argv[]) {
    // ── Parse CLI arguments ─────────────────────────────────────────────────
    std::string scenario_id = "UNIVERSAL_BASELINE";
    std::string replay_path;
    std::string print_payload_path;
    std::string sign_scenario_path;
    std::string sign_key_path;
    std::vector<std::string> plugin_paths;   // --plugin (tekrarlanabilir, sira korunur)
    bool        interactive = false;
    bool        det_mode    = false;
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "--scenario" && i + 1 < argc) {
            scenario_id = argv[++i];
        } else if (arg == "--intel-replay" && i + 1 < argc) {
            replay_path = argv[++i];
        } else if (arg == "--print-scenario-payload" && i + 1 < argc) {
            print_payload_path = argv[++i];
        } else if (arg == "--sign-scenario" && i + 1 < argc) {
            sign_scenario_path = argv[++i];
        } else if (arg == "--key" && i + 1 < argc) {
            sign_key_path = argv[++i];
        } else if (arg == "--interactive" || arg == "--repl") {
            interactive = true;
        } else if (arg == "--json-stdout") {
            g_json_stdout = true;
        } else if (arg == "--det-mode") {
            det_mode = true;
        } else if (arg == "--plugin") {
            // Tekrarlanabilir: --plugin a.dll --plugin b.so ... Path'ler verildikleri
            // (deterministik) sirada saklanir ve ayni sirada yuklenir.
            if (i + 1 >= argc) {
                std::cerr << "[ENGINE] '--plugin' icin yol argumani eksik.\n"
                          << "         Kullanim: --plugin <path> [--plugin <path> ...]\n";
                return 2;  // CLI kullanim hatasi
            }
            plugin_paths.emplace_back(argv[++i]);
        } else if (arg == "--help" || arg == "-h") {
            std::cout << "Kullanim: caelus_os [--scenario <id>] [--intel-replay <path>] [--plugin <path> ...] [--interactive|--repl] [--det-mode]\n"
                      << "  --scenario <id>   Senaryo profil kimligini belirtir "
                         "(varsayilan: UNIVERSAL_BASELINE)\n"
                      << "  --intel-replay <path> CSV/JSONL kriz kaydini tick-zamanli oynatir\n"
                      << "  --plugin <path>   Dinamik eklenti (.dll/.so) yukler; TEKRARLANABILIR,\n"
                      << "                    verilen sirada islenir. T-18 imza gate'i uygulanir:\n"
                      << "                    <path>.sig sidecar'i (ed25519, pinli guven capasi,\n"
                      << "                    'caelus_sign_scenario --sign-plugin' ile uretilir)\n"
                      << "                    gecerli degilse eklenti REDDEDILIR (fail-closed).\n"
#ifndef CAELUS_PRODUCTION
                      << "                    Gelistirme icin CAELUS_PLUGIN_ALLOW_UNVERIFIED=1.\n"
#endif
                      << "  --print-scenario-payload <json> Imzalanacak canonical payload'u stdout'a basar\n"
                      << "  --sign-scenario <json> --key <seed> Ed25519 signer FFI olmadigi icin blocker raporlar\n"
                      << "  --interactive     Senaryo REPL'i baslatir (geriye uyumlu bayrak)\n"
                      << "  --repl            Senaryo REPL'i baslatir\n"
                      << "  --json-stdout     snapshot --json icin prefixsiz saf JSON satiri basar\n"
                      << "  --det-mode        Deterministik CI modu: sanal saat + tohumlu PRNG,\n"
                      << "                    CDET: bloku stdout'a basilir, agi atlar.\n";
            return 0;
        }
    }
    if (!print_payload_path.empty()) {
        return PrintScenarioCanonicalPayload(print_payload_path);
    }
    if (!sign_scenario_path.empty()) {
        return ReportScenarioSignerBlocked(sign_scenario_path, sign_key_path);
    }
    std::cout << "==============================================================\n";
    std::cout << "      CAELUS OS — Air-Gapped Neuro-Symbolic LMOS\n";
    std::cout << "      Universal Causal Crisis Engine\n";
    std::cout << "      Senaryo : " << scenario_id << "\n";
#ifdef CAELUS_EMBEDDED_UI
    std::cout << "      BUILD MODE: BLACKBOX (UI Embedded)\n";
#else
    std::cout << "      BUILD MODE: DEVELOPMENT (External UI Files)\n";
#endif
    std::cout << "==============================================================\n";

    // ── Deterministic mode setup ───────────────────────────────────────────
    // In --det-mode: inject fixed seed + freeze virtual clock so every run
    // produces byte-identical computation output.  No network ops, no WS.
    if (det_mode) {
        // Fixed CI seed — NOT a production secret.
        caelus_setenv("CAELUS_DET_SEED",    "0xCAE105DEADBEEF00");
        // Fixed CI enclave key (64 hex chars = 32 bytes AES-256).
        // Enables deterministic AES-CBC IVs when profile blobs are present.
        caelus_setenv("CAELUS_ENCLAVE_KEY",
            "cae1cae1cae1cae1cae1cae1cae1cae1"
            "cae1cae1cae1cae1cae1cae1cae1cae1");
        // Fixed CI identity seed so audit SESSION_START fingerprint is
        // deterministic. This is a public test vector, never a production key.
        caelus_setenv("CAELUS_IDENTITY_KEY_HEX",
            "c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1"
            "c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1");
        // Freeze Rust discovery clock at UNIX epoch 0.
        caelus_clock_set_virtual(0);
        std::cout << "[DET] Deterministik mod aktif — tohumlu PRNG + sanal saat(0)\n";
    }

    // ── Start War Room WebSocket emitter ───────────────────────────────────
    // Varsayılan: 127.0.0.1 (air-gapped, loopback). Opsiyonel UZAK MOD:
    // CAELUS_WARROOM_REMOTE=1 → LAN'a (0.0.0.0) bağlanır ve embedded UI'ı aynı
    // portta HTTP ile sunar; böylece aynı WiFi'daki telefon canlı motoru açar.
    // FAIL-CLOSED: CAELUS_WARROOM_TOKEN yoksa uzak moda GEÇİLMEZ (loopback'te
    // kalır). Token, HTTP sayfası ve WS bağlantısının ikisinde de zorunludur.
    // Uyarı: TLS yok — token LAN'da düz metin gider; yalnız güvendiğiniz yerel
    // ağda kullanın. --det-mode'da tümü atlanır (CI/port çakışması yok).
    if (!det_mode) {
        const char* remote_env = std::getenv("CAELUS_WARROOM_REMOTE");
        const bool want_remote = remote_env && (remote_env[0] == '1' ||
            std::strcmp(remote_env, "true") == 0 || std::strcmp(remote_env, "yes") == 0);
        const char* token_env = std::getenv("CAELUS_WARROOM_TOKEN");
        const std::string token = (token_env && token_env[0]) ? token_env : "";

        bool remote = false;
        if (want_remote) {
#ifndef CAELUS_EMBEDDED_UI
            std::cerr << "[WS-EMITTER] UZAK MOD reddedildi: bu derlemede gomulu UI yok "
                         "(CAELUS_EMBEDDED_UI). Loopback'te devam ediliyor.\n";
#else
            if (token.empty()) {
                std::cerr << "[WS-EMITTER] UZAK MOD reddedildi (FAIL-CLOSED): "
                             "CAELUS_WARROOM_TOKEN ayarli degil. Kimlik dogrulamasi "
                             "olmadan LAN'a acilmaz. Loopback'te devam ediliyor.\n"
                             "  Ornek: set CAELUS_WARROOM_TOKEN=<uzun-gizli-dize>\n";
            } else {
                caelus::WsEmitter::Config cfg;
                cfg.bind_all = true;
                cfg.token    = token;
                g_emitter.configure(cfg);
                g_emitter.add_http_route("/", "text/html; charset=utf-8",
                    CAELUS_UI_HTML, CAELUS_UI_HTML_LEN);
                g_emitter.add_http_route("/scenario_compiler.js", "application/javascript; charset=utf-8",
                    CAELUS_SCENARIO_COMPILER_JS, CAELUS_SCENARIO_COMPILER_JS_LEN);
                g_emitter.add_http_route("/app.js", "application/javascript; charset=utf-8",
                    CAELUS_UI_JS, CAELUS_UI_JS_LEN);
                remote = true;
            }
#endif
        }

        g_emitter.start(47809);

        if (remote) {
            std::cout << "\n[UZAK WAR ROOM] Telefon/tablet ayni WiFi'dan acsin:\n"
                      << "  http://<BU-BILGISAYARIN-LAN-IP>:47809/?token=" << token << "\n"
                      << "  (LAN IP'yi bul: Windows 'ipconfig', Linux/mac 'ip addr'/'ifconfig')\n"
                      << "  Token, sayfa VE WS baglantisi icin zorunlu; yanlis/eksik token reddedilir.\n"
                      << "  NOT: TLS yok — yalnizca guvendiginiz yerel agda kullanin.\n\n";
        }
    }

    // ── Bootstrap Plugin Registry ──────────────────────────────────────────
    // Bind engine services (emitter, tick counter) so plugins can call back.
    // Then select solver + default connector/reporter based on mode.
    g_registry.bind_engine(&g_emitter, &g_tick_ctr);
    if (det_mode) {
        // DeterministicSolver + NullReporter — clean, noise-free CI output.
        g_registry.bootstrap_det();
    } else {
        // Best available solver (ORToolsSolver if linked, else Deterministic).
        g_registry.bootstrap();
    }

    // ── KEYMGMT köprüsü (T-23'ün C++ yarısı) ───────────────────────────────────
    // Rust kayıt fonksiyonunu registry'ye enjekte et — PLUGIN YÜKLEMEDEN ÖNCE.
    // Bir eklenti KEYMGMT sınıfı (CAELUS_PLUGIN_KEYMGMT) bildirip kaydolursa
    // registry, statik trampolinlerini caelus_keymgmt_register'a delege olarak
    // kaydeder (state = registry; çağrılar guard'lı protect_key/unprotect_key
    // üzerinden vtable'a iner). KEYMGMT eklentisi yoksa HİÇBİR ŞEY kaydedilmez
    // → Rust'taki DPAPI (Windows) / env (POSIX) fallback'i bit-bit aynı çalışır.
    // Shutdown/unload'da delege NULL/NULL ile temizlenir (dangling fn ptr yok).
    g_registry.set_keymgmt_bridge(&caelus_keymgmt_register);

    // ── Dinamik Eklenti Yukleme (T-17 LOADER-WIRE) ─────────────────────────────
    // Sira: registry kurulumu (yukarida) → BURADA eklenti enjeksiyonu →
    //       connector cozumlemesi + senaryo yuklemesi → tick dongusu.
    // Eklentiler tick dongusu baslamadan once kayitlandigi icin solver/connector/
    // reporter/listener slotlari ilk tick'te hazirdir. Bir eklenti SOLVER sinifi
    // bildirirse bootstrap'in varsayilan solver'ini override eder (kasitli).
    //
    // GUVENLIK — T-18 imza gate'i + URETIM VERIFIER'I (bu dalga ile):
    //   Artik gercek bir ed25519 verifier KAYITLIDIR (VerifyPluginSignatureProd):
    //   "<plugin>.sig" sidecar'i okunur, "ed25519:<pub>:<sig>" parse edilir,
    //   pubkey PINLI guven capasiyla (CAELUS_TRUSTED_PLUGIN_PUBKEY) karsilastirilir
    //   ve "CAELUS_PLUGIN_V1\n"||ham-bytes mesaji ed25519 ile dogrulanir.
    //   Sidecar yok / parse hatasi / pin uyusmazligi / imza gecmezse eklenti
    //   REDDEDILIR ([PLUGIN-SIG] nedeni + UNVERIFIED_PLUGIN_REJECTED, fail-closed).
    //
    // DEV BYPASS DAVRANISI KORUNUR (T-18):
    //   CAELUS_PLUGIN_ALLOW_UNVERIFIED=1 set ise verifier KAYDEDILMEZ; boylece
    //   DynamicPluginLoader header'indaki mevcut dev-bypass yolu (kendi uyari
    //   loguyla) bire bir ayni calisir. Header'daki gate mantigi degismedi.
    //
    // GUVENLI VARSAYILAN — fail-closed:
    //   Air-gapped/kurcalanamaz felsefe geregi, acikca istenen ('--plugin') bir
    //   eklentinin guvenle yuklenememesi (imza reddi, ABI uyumsuzlugu, dosya yok)
    //   FATAL'dir: motor net hata basar ve sifirdan farkli cikis kodu (4) dondurur.
    //   Bu, "eklentiyi istedim ama sessizce atlandi" belirsizligini ortadan kaldirir.
    //
    // DETERMINIZM (T-10): yalniz CLI sirasi kullanilir; duvar saati/rastgelelik YOK.
    // Loader, main boyunca yasar; '--plugin' verilmemisse hicbir yan etki yoktur.
    caelus::DynamicPluginLoader plugin_loader;
#ifdef CAELUS_PRODUCTION
    // CAELUS_PRODUCTION: CAELUS_PLUGIN_ALLOW_UNVERIFIED verifier-kayit-atlama yolu derleme-disi — uretim verifier'i KOSULSUZ kayitli, imzasiz plugin asla yuklenemez.
    plugin_loader.set_signature_verifier(&VerifyPluginSignatureProd);
    if (!plugin_paths.empty()) {
        std::cout << "[PLUGIN-SIG] Uretim ed25519 verifier aktif "
                     "(sidecar .sig + pinli guven capasi; CAELUS_PRODUCTION).\n";
    }
#else
    {
        // Header'daki allow_unverified_plugins_for_dev() ile ayni katilikta
        // kontrol: yalniz tam olarak "1" bypass sayilir.
        const char* allow_unverified = std::getenv("CAELUS_PLUGIN_ALLOW_UNVERIFIED");
        const bool  dev_bypass = allow_unverified && std::strcmp(allow_unverified, "1") == 0;
        if (!dev_bypass) {
            plugin_loader.set_signature_verifier(&VerifyPluginSignatureProd);
            if (!plugin_paths.empty()) {
                std::cout << "[PLUGIN-SIG] Uretim ed25519 verifier aktif "
                             "(sidecar .sig + pinli guven capasi).\n";
            }
        } else if (!plugin_paths.empty()) {
            std::cerr << "[PLUGIN-SIG] UYARI: CAELUS_PLUGIN_ALLOW_UNVERIFIED=1 — "
                         "uretim verifier kaydedilmedi (dev bypass yolu aktif).\n";
        }
    }
#endif
    if (!plugin_paths.empty()) {
        std::cout << "\n[PLUGIN] " << plugin_paths.size()
                  << " dinamik eklenti istegi isleniyor (deterministik sira)...\n";
        for (const std::string& plugin_path : plugin_paths) {
            if (!plugin_loader.load_into_registry(plugin_path, g_registry)) {
                std::cerr << "[ENGINE] FATAL: dinamik eklenti guvenle yuklenemedi: "
                          << plugin_path << "\n"
                          << "         (T-18 imza gate / ABI uyumsuzlugu / dosya hatasi — fail-closed)\n";
                g_emitter.stop();   // baslamadiysa no-op; baslamissa loopback soketini kapatir
                return 4;            // eklenti guvenli-yukleme hatasi
            }
        }
        std::cout << "[PLUGIN] " << plugin_loader.loaded_count()
                  << " dinamik eklenti basariyla kaydedildi (T-18 imza gate gecti).\n";
    }

    std::string html_out, compiler_out, js_out;
#ifdef CAELUS_EMBEDDED_UI
    const char* tmp = std::getenv("TEMP");
    if (!tmp) tmp = std::getenv("TMP");
    if (!tmp) tmp = ".";
    html_out = std::string(tmp) + "/caelus_ui.html";
    compiler_out = std::string(tmp) + "/scenario_compiler.js";
    js_out   = std::string(tmp) + "/app.js";

    std::cout << "\n[UI] Stratejik Arayuz bellege cikartiliyor...\n";
    if (DumpEmbeddedUI(html_out, compiler_out, js_out)) {
        std::cout << "[UI] Arayuz hazir -> " << html_out << "\n";
        std::cout << "[UI] (Bu dosyalar cikista silinecektir.)\n";
    } else {
        std::cout << "[UI] Arayuz cikartilamadi (tmp dizini yazilabilir degil?)\n";
    }
#endif

    // Phase 1: Authenticate field devices via Shadow-Mesh (Rust FFI).
    // Skipped in --det-mode: ephemeral ed25519 keypairs are always unique;
    // including them would make the output non-deterministic.
    if (!det_mode) {
        RunShadowMeshHandshake();
    }

    // Phase 1.5: Operational risk profiling — profil yükleme.
    caelus::intel::ProfileManager intel_mgr;
    auto profile = intel_mgr.LoadProfile(scenario_id);

    // ── Causal Engine v2 — Graf tabanlı sürtünme (R1) ─────────────────────
    // Ağırlıklı doğrusal toplam (CalculateFrictionMultiplier) artık kullanılmıyor.
    // Nedensel graf: her risk faktörü bir düğümdür; kenarlar çarpan taşır;
    // geri besleme döngüleri kendi kendine büyür; histerezis kalıcı değişim yaratır.
    caelus::causal::CausalEngine causal_engine;
    if (det_mode) causal_engine.set_prng_seed(0xCAE105DEADBEEF00ULL);
    ConnectorIntelBridge connector_bridge{&causal_engine};
    g_registry.bind_intel_injector(&connector_bridge, &InjectConnectorIntel);

    // Intel veri düzlemi imza doğrulayıcısı: Rust ed25519 FFI'si kancaya
    // kurulur. Pin (CAELUS_TRUSTED_INTEL_PUBKEY) set iken kapı bu doğrulayıcı
    // olmadan hiçbir payload kabul etmez (fail-closed); kurulum connector
    // do_init'lerinden ÖNCE olmalıdır.
    caelus::connector_detail::set_intel_sig_verifier(&caelus_verify_scenario_signature);

    // Live connectors are opt-in and registered only after the concrete engine
    // intel sink is bound. Their reader threads enqueue events; engine ticks
    // drain them through dispatch_connectors() on the main causal path.
    caelus::MqttConnector mqtt_connector;
    caelus::ZapierWebhookConnector zapier_connector;
    const bool enable_mqtt = caelus_env_enabled("CAELUS_ENABLE_MQTT_CONNECTOR");
    const bool enable_zapier = caelus_env_enabled("CAELUS_ENABLE_ZAPIER_CONNECTOR");
    if (!det_mode && enable_mqtt) {
        g_registry.add_connector(caelus::MqttConnector::make_vtable(), &mqtt_connector);
    } else if (det_mode && enable_mqtt) {
        std::cout << "[CONNECTOR] MqttConnector det-mode nedeniyle atlandi.\n";
    }
    if (!det_mode && enable_zapier) {
        g_registry.add_connector(caelus::ZapierWebhookConnector::make_vtable(),
                                 &zapier_connector);
    } else if (det_mode && enable_zapier) {
        std::cout << "[CONNECTOR] ZapierWebhookConnector det-mode nedeniyle atlandi.\n";
    }

    // ── Senaryo Paketi Yükleme (R2) ──────────────────────────────────────
    // scenarios/<scenario_id>.json varsa: paketten nedensel grafı yükle.
    // Yoksa: evrensel boş şablonda AWAITING_SCENARIO_INJECTION olarak bekle.
    caelus::ScenarioPack scenario_pack;
    const std::string pack_path = "scenarios/" + scenario_id + ".json";
    const bool pack_loaded = scenario_pack.load(pack_path);
    const bool awaiting_scenario = !pack_loaded;
    std::string awaiting_state_json;

    // War Room canlı snapshot yayınının kullandığı aktif senaryo kimliği.
    g_scenario_id = pack_loaded ? scenario_pack.id : scenario_id;

    if (pack_loaded) {
        // Paket grafını motora uygula (reset() + tüm düğüm/kenar/döngü yükle)
        scenario_pack.apply_to_engine(causal_engine);
        // v1 uyum köprüsü: paket profilini aktif profil olarak kullan
        *profile = scenario_pack.risk_profile;
        g_emitter.emit(caelus::ws_json::scenario_loaded(
            scenario_pack.id, scenario_pack.region));
        // Gerçek graf durumunu (düğüm/kenar) hemen yayınla: UI'ın causal graph
        // ve analiz paneli yüklenir yüklenmez motorun canlı verisiyle dolar.
        emit_ws_snapshot(causal_engine, g_scenario_id);
        std::cout << "[SCENARIO] Domain: " << scenario_pack.sector
                  << " | Ufuk: " << scenario_pack.horizon_hours << " saat"
                  << " | Tick: " << scenario_pack.tick_minutes << " dak\n";
    } else {
        causal_engine.load_universal_blank_slate();
        awaiting_state_json = caelus::ws_json::engine_state(
            "AWAITING_SCENARIO_INJECTION", scenario_id, causal_engine.current_tick(), 1.0);
        g_emitter.emit(awaiting_state_json);
        std::cout << "[STATE] AWAITING SCENARIO INJECTION — blank slate active, "
                  << "friction=1.000000x, no crisis flow.\n";
    }

    // ── Connector Replay Kaydı (R8) ────────────────────────────────────────
    // ScenarioPack intel_feed_sequence ve opsiyonel CSV/JSONL replay dosyaları
    // aynı PluginRegistry hattından CausalEngine'e enjekte edilir.
    caelus::CsvReplayConnector scenario_replay_connector;
    if (pack_loaded) {
        scenario_replay_connector.source_path = pack_path.c_str();
        g_registry.add_connector(caelus::CsvReplayConnector::make_vtable(),
                                 &scenario_replay_connector);
    }
    caelus::CsvReplayConnector file_replay_connector;
    if (pack_loaded && !replay_path.empty() && replay_path != pack_path) {
        file_replay_connector.source_path = replay_path.c_str();
        g_registry.add_connector(caelus::CsvReplayConnector::make_vtable(),
                                 &file_replay_connector);
    } else if (!pack_loaded && !replay_path.empty()) {
        std::cout << "[CONNECTOR] Replay kaydı bekletildi: önce geçerli imzalı senaryo gerekir.\n";
    }

    auto run_causal_tick = [&]() noexcept -> caelus::causal::EngineSnapshot {
        const uint64_t tick = causal_engine.current_tick();
        g_tick_ctr.store(tick, std::memory_order_relaxed);
        const size_t delivered = g_registry.dispatch_connectors();
        if (delivered > 0) {
            std::cout << "[CONNECTOR] Tick " << tick << ": "
                      << delivered << " intel olayi enjekte edildi.\n";
        }
        audit_intel_rejections();
        return causal_engine.tick();
    };

    caelus::causal::EngineSnapshot causal_snap = run_causal_tick();

    bool   regime_exceeded    = causal_snap.regime_exceeded;
    double raw_friction        = causal_snap.raw_friction_d();
    double friction_mult       = causal_snap.clamped_friction_d();
    double causal_post_intel   = friction_mult; // güncellenir: intel sonrası

    std::cout << "[CAUSAL-v2] Baseline sürtünme (tick=1):\n"
              << "            Ham  : " << std::fixed << std::setprecision(6)
              << raw_friction << "x\n"
              << "            Kenet: " << friction_mult << "x\n"
              << "            Durum: " << causal_snap.summary << "\n";

    // Baseline sürtünmesini denetim günlüğüne kaydet
    {
        std::ostringstream ss;
        ss << std::fixed << std::setprecision(6);
        ss << "{\"type\":\"CAUSAL_BASELINE\","
           << "\"raw_friction\":" << raw_friction
           << ",\"clamped_friction\":" << friction_mult
           << ",\"tick\":" << causal_engine.current_tick()
           << ",\"regime_exceeded\":" << (regime_exceeded ? "true" : "false") << "}";
        g_audit.append(ss.str());
    }

    if (regime_exceeded) {
        std::cerr << "[CRITICAL] REGIME_EXCEEDED (baseline): "
                  << raw_friction << "x > 3.0x\n";
        std::string re_json = caelus::ws_json::regime_exceeded(raw_friction, 3.0);
        g_emitter.emit(re_json);
        g_audit.append(re_json);
    }

    // Phase 1.6: Persistent local device identity (stable fingerprint across boots).
    const std::string key_path = "caelus_identity.key";
    CaelusIdentityHandle* local_id = caelus_identity_load_or_create(
        reinterpret_cast<const uint8_t*>(key_path.data()), key_path.size());
    if (!local_id) {
        std::cout << "[WARN] Persistent identity unavailable; using ephemeral identity.\n";
        local_id = caelus_identity_new();
    }

    // ── Denetim Günlüğü Açılışı (R6) ─────────────────────────────────────────
    // Production: session_id gerçek duvar saatiyle adli benzersizlik sağlar.
    // --det-mode: genesis hash CDET audit_chain_head'e girdiği için session_id
    // sabitlenir; aksi halde iki CI koşumu farklı zincir başı üretir.
    const uint64_t audit_session_id =
        det_mode ? 0ULL : static_cast<uint64_t>(std::time(nullptr));
    const std::string audit_path    = caelus::AuditLog::make_log_path(audit_session_id);
    if (g_audit.open(local_id, audit_session_id, audit_path)) {
        // SESSION_START: kimlik parmak izi + senaryo bilgisi
        uint8_t fp[32] = {};
        caelus_identity_fingerprint(local_id, fp);
        std::ostringstream ss_start;
        ss_start << std::hex << std::setfill('0');
        ss_start << "{\"type\":\"SESSION_START\",\"scenario\":\"" << json_escape(scenario_id)
                 << "\",\"sector\":\"" << json_escape(profile->region)
                 << "\",\"fingerprint\":\"";
        for (int i = 0; i < 32; ++i)
            ss_start << std::setw(2) << static_cast<unsigned>(fp[i]);
        ss_start << "\",\"det_mode\":" << (det_mode ? "true" : "false") << "}";
        g_audit.append(ss_start.str());
        if (awaiting_scenario && !awaiting_state_json.empty()) {
            g_audit.append(awaiting_state_json);
        }
        // T-17: Yuklenen dinamik eklentileri denetim zincirine deterministik
        // olarak isle. Buraya ulasildiysa fail-closed geregi tum '--plugin'
        // istekleri basariyla yuklenmistir (sonuc daima "ok"). Yalniz path +
        // sonuc kaydedilir; duvar saati/rastgelelik EKLENMEZ (T-10 korunur).
        for (const std::string& plugin_path : plugin_paths) {
            std::ostringstream ss_plugin;
            ss_plugin << "{\"type\":\"PLUGIN_LOADED\",\"path\":\""
                      << json_escape(plugin_path) << "\",\"result\":\"ok\"}";
            g_audit.append(ss_plugin.str());
        }
    }

    // Phase 1.7: Shadow-Mesh discovery + Intel Feed bridge.
    constexpr uint64_t LOCAL_SLOT = 0x202606070099ULL;
    CaelusDiscoveryCtx* disc_ctx = caelus_discovery_new(local_id, LOCAL_SLOT);

    // Tracked for the deterministic CI output block (outer scope so CDET can read them).
    double last_field_coeff  = 0.0;
    int    last_crisis_level = 0;
    double last_field_mult   = 0.0;

    if (disc_ctx) {
        std::cout << "\n[INTEL-FEED] -- Shadow-Mesh -> Intel-Core Bridge --------\n";

        // Best-effort: start the real UDP multicast loops. Non-fatal on failure
        // (e.g. no LAN / port busy) — the rest of the cycle still runs.
        // Skipped in --det-mode: UDP timing is non-deterministic.
        if (!det_mode) {
        if (caelus_discovery_start(disc_ctx)) {
            std::cout << "[INTEL-FEED] UDP multicast discovery started (224.0.0.251:47808).\n";
        } else {
            std::cout << "[INTEL-FEED] Discovery loop not started (no interface / port busy).\n";
            }
        }

        if (pack_loaded) {
            // Synthetic integration vector: a generic field observation.
            // Blank-slate mode intentionally receives no synthetic signal.
            uint8_t actor_fp[32] = {};
            for (int i = 0; i < 32; ++i) actor_fp[i] = static_cast<uint8_t>(0x4D + i);
            const char memo[] = "GENERIC_FIELD_SIGNAL: Actor_Alpha elevated friction";
        caelus_inject_intel_packet(
                disc_ctx, 0xCAE10001ULL, actor_fp,
            820000,    // friction coefficient 0.82 (fixed-point), Rust-clamped to ≤1.0
            2,         // crisis_level HIGH
            reinterpret_cast<const uint8_t*>(memo), std::strlen(memo));
        } else {
            std::cout << "[INTEL-FEED] AWAITING SCENARIO INJECTION — synthetic signal skipped.\n";
        }

        IntelFeedPacket pkt {};
        while (caelus_fetch_intel_feed(disc_ctx, &pkt)) {
            double field_coeff = pkt.friction_coefficient_fp / 1'000'000.0;
            last_field_coeff  = field_coeff;
            last_crisis_level = static_cast<int>(pkt.crisis_level);

            std::cout << "[INTEL-FEED] Paket alındı:\n";
            std::cout << "             Session ID    : 0x" << std::hex << pkt.session_id << std::dec << "\n";
            std::cout << "             Crisis Level  : " << static_cast<int>(pkt.crisis_level) << "\n";
            std::cout << "             Field coeff   : " << std::fixed << std::setprecision(4) << field_coeff << "\n";
            std::cout << "             Memo          : " << reinterpret_cast<const char*>(pkt.memo) << "\n";

            // ── Causal Engine v2: Intel → Nedensel Graf ──────────────────────
            // Eski yol: FieldMultiplierFromPacket(coeff, level) formülü (KALDIRILDI)
            // Yeni yol: Intel paketi graf düğümlerini günceller; sürtünme
            //           bir sonraki run_ticks() içinde yeniden hesaplanır.
            causal_engine.inject_intel_fp(
                pkt.friction_coefficient_fp,
                static_cast<int>(pkt.crisis_level),
                reinterpret_cast<const char*>(pkt.memo));

            // War Room telemetrisi + denetim günlüğü
            std::string intel_json = caelus::ws_json::intel_event(
                pkt.session_id,
                static_cast<int>(pkt.crisis_level),
                field_coeff,
                reinterpret_cast<const char*>(pkt.memo));
            g_emitter.emit(intel_json);
            g_audit.append(intel_json);
        }

        // ── Causal Engine: Intel sonrası yeniden yayılım ─────────────────────
        // Enjekte edilen verinin graf üzerindeki etkisini 2 tick boyunca yayılır.
        for (uint32_t i = 0; i < 2; ++i) {
            causal_snap = run_causal_tick();
        }
        friction_mult  = causal_snap.clamped_friction_d();
        raw_friction   = causal_snap.raw_friction_d();
        regime_exceeded= causal_snap.regime_exceeded;
        causal_post_intel = friction_mult;
        last_field_mult   = friction_mult; // eski alan artık post-intel sürtünme

        std::cout << "[CAUSAL-v2] Intel sonrası sürtünme (tick=3):\n"
                  << "            Ham  : " << std::fixed << std::setprecision(6)
                  << raw_friction << "x\n"
                  << "            Kenet: " << friction_mult << "x\n"
                  << "            Durum: " << causal_snap.summary << "\n";

        if (regime_exceeded) {
            std::string re_json = caelus::ws_json::regime_exceeded(raw_friction, 3.0);
            g_emitter.emit(re_json);
            g_audit.append(re_json);
        }

        // War Room: güncel friction
        std::string fr_json = caelus::ws_json::friction(friction_mult,
            causal_snap.outage_active ? 3 : (regime_exceeded ? 2 : 0),
            causal_engine.current_tick());
        g_emitter.emit(fr_json);
        // Post-intel sürtünme denetim günlüğüne (friction JSON yeterli)
        {
            std::ostringstream ss;
            ss << std::fixed << std::setprecision(6);
            ss << "{\"type\":\"INTEL_POST_FRICTION\","
               << "\"clamped_friction\":" << friction_mult
               << ",\"outage\":" << (causal_snap.outage_active ? "true" : "false")
               << ",\"tick\":" << causal_engine.current_tick() << "}";
            g_audit.append(ss.str());
        }

        caelus_discovery_stop(disc_ctx);
        caelus_discovery_free(disc_ctx);
        disc_ctx = nullptr;
    }

    // Phase 2: Optimise the generic cycle via the active solver plugin.
    const caelus::SolverResult opt_res = RunOptimizationCycle(friction_mult);

    // Çözüm sonucunu denetim günlüğüne kaydet
    {
        std::ostringstream ss;
        ss << "{\"type\":\"SOLVER_RESULT\","
           << "\"solver\":\"" << g_registry.solver_name() << "\","
           << "\"on_time\":"  << (opt_res.on_time ? "true" : "false") << ","
           << "\"completion_min\":" << opt_res.completion << ","
           << "\"friction_mult\":" << std::fixed << std::setprecision(6) << friction_mult
           << "}";
        g_audit.append(ss.str());
    }

    // Phase 2.5: Dispatch the completed-cycle report to all reporter plugins.
    if (!det_mode) {
        CaelusReportPayload rpt{};
        std::strncpy(rpt.scenario_id, scenario_id.c_str(), sizeof(rpt.scenario_id) - 1);
        rpt.final_friction   = friction_mult;
        rpt.completion_min   = opt_res.completion;
        rpt.on_time          = opt_res.on_time;
        rpt.regime_exceeded  = opt_res.regime_exceeded || regime_exceeded;
        rpt.tick_nr          = g_tick_ctr.fetch_add(1, std::memory_order_relaxed);
        g_registry.dispatch_report(rpt);
    }

    if (interactive) {
        causal_snap = RunScenarioRepl(
            causal_engine, scenario_pack, pack_loaded, scenario_id, causal_snap);
        friction_mult       = causal_snap.clamped_friction_d();
        raw_friction        = causal_snap.raw_friction_d();
        regime_exceeded     = causal_snap.regime_exceeded;
        causal_post_intel   = friction_mult;
    }

    caelus_identity_free(local_id);

    std::cout << "\n[OK] CAELUS OS cycle complete.\n";

    // ── Deterministic CI output block ──────────────────────────────────────────
    // In --det-mode, print a structured block of pure computation results.
    // The CI script extracts lines starting with "CDET:" and hashes them;
    // two runs with the same inputs must produce the same hash.
    // Values: only deterministic math outputs — no timestamps, keys, or UUIDs.
    if (det_mode) {
        std::cout << std::fixed;
        std::cout << "\nCDET: BLOCK_BEGIN\n";
        std::cout << "CDET: scenario="                << scenario_id                       << "\n";
        std::cout << "CDET: scenario_state="          << (awaiting_scenario ? "AWAITING_SCENARIO_INJECTION" : "SCENARIO_ACTIVE") << "\n";
        std::cout << "CDET: region="                  << profile->region                   << "\n";
        std::cout << "CDET: bureaucratic_complexity=" << std::setprecision(6) << profile->bureaucratic_complexity  << "\n";
        std::cout << "CDET: historical_delay_rate="   << std::setprecision(6) << profile->historical_delay_rate   << "\n";
        std::cout << "CDET: labor_action_probability="<< std::setprecision(6) << profile->labor_action_probability<< "\n";
        std::cout << "CDET: route_congestion="        << std::setprecision(6) << profile->route_congestion        << "\n";
        std::cout << "CDET: weather_severity="        << std::setprecision(6) << profile->weather_severity        << "\n";
        // Causal Engine v2 değerleri (int64_t fixed-point aritmetiğinden çıkar → deterministik)
        std::cout << "CDET: raw_friction="                 << std::setprecision(6) << raw_friction      << "\n";
        std::cout << "CDET: clamped_friction="             << std::setprecision(6)
                  << caelus::causal::fp_to_d(causal_snap.clamped_friction_fp)                           << "\n";
        std::cout << "CDET: regime_exceeded="              << (regime_exceeded ? "true" : "false")      << "\n";
        std::cout << "CDET: causal_engine_ticks="          << causal_engine.current_tick()              << "\n";
        std::cout << "CDET: field_friction_coeff="         << std::setprecision(6) << last_field_coeff  << "\n";
        std::cout << "CDET: field_crisis_level="           << last_crisis_level                         << "\n";
        std::cout << "CDET: causal_post_intel_friction="   << std::setprecision(6) << causal_post_intel << "\n";
        std::cout << "CDET: final_friction="               << std::setprecision(6) << friction_mult     << "\n";
        std::cout << "CDET: travel_band_low="         << opt_res.travel_low                                      << "\n";
        std::cout << "CDET: travel_band_high="        << opt_res.travel_high                                     << "\n";
        std::cout << "CDET: arrival_min="             << opt_res.arrival                                        << "\n";
        std::cout << "CDET: completion_min="          << opt_res.completion                                     << "\n";
        std::cout << "CDET: on_time="                 << (opt_res.on_time ? "true" : "false")                   << "\n";
        // Denetim zinciri başını CDET bloğuna dahil et (deterministik hash kanıtı)
        std::cout << "CDET: audit_chain_head="    << g_audit.chain_head_hex()   << "\n";
        std::cout << "CDET: audit_entry_count="   << g_audit.entries()          << "\n";
        std::cout << "CDET: BLOCK_END\n";
        // Restore wall-clock for any code that runs after this point.
        caelus_clock_use_real();
    }

    // SESSION_END kaydı + denetim günlüğünü mühürle (ed25519 imzası + flush).
    // Bu, adli kanıt niteliğindeki zinciri tamamlar.
    if (g_audit.is_open()) {
        std::ostringstream ss;
        ss << "{\"type\":\"SESSION_END\","
           << "\"scenario\":\"" << json_escape(scenario_id) << "\","
           << "\"audit_entries\":" << g_audit.entries()
           << ",\"log_path\":\"" << json_escape(g_audit.path()) << "\"}";
        g_audit.append(ss.str());
        g_audit.seal();  // ed25519 imzası + flush
    }

    // Shutdown plugin registry (calls cleanup on all registered plugins),
    // then flush final telemetry and close the War Room bridge.
    g_registry.shutdown();
    g_emitter.stop();

#ifdef CAELUS_EMBEDDED_UI
    // Cleanup: remove the extracted cleartext UI so nothing persists on disk.
    if (!html_out.empty()) std::remove(html_out.c_str());
    if (!compiler_out.empty()) std::remove(compiler_out.c_str());
    if (!js_out.empty())   std::remove(js_out.c_str());
#endif
    return 0;
}
