//
//  KeyProtection.swift
//  CAELUSMobileCore
//
//  Bridges the process-wide native key-protection delegate
//  (caelus_mobile_register_key_protection_v1) to a Swift provider.
//
//  Threat-model contract: the 32-byte device identity seed is generated by
//  the Rust identity layer and must never be persisted in plaintext.  The
//  provider wraps it (on iOS: AES-GCM with a Keychain-guarded wrapping key)
//  and unwraps it on load.  Raw seed bytes exist only inside the native
//  callback frame — SwiftUI/feature code never sees a private key, only
//  this narrow provider interface does.
//
import CaelusBridgeC
import Foundation

/// Result of protecting a raw seed: opaque wrapped bytes plus the format
/// tag that must round-trip back into `unprotect`.
public struct ProtectedKeyMaterial: Sendable, Equatable {
    public var bytes: [UInt8]
    public var format: UInt32

    public init(bytes: [UInt8], format: UInt32) {
        self.bytes = bytes
        self.format = format
    }
}

/// Well-known key blob format tags (mirror of the plugin ABI values).
public enum KeyBlobFormat {
    /// Plaintext 32-byte identity seed (input side only).
    public static let rawSeed: UInt32 = 0x0000_0001
    /// OS-keystore wrapped (the iOS Keychain/CryptoKit provider).
    public static let protectedOS: UInt32 = 0x0000_0002
}

/// Platform key-protection provider.  Implementations must be pure
/// functions of their inputs plus platform key material: no logging of
/// plaintext, no retention of the seed.
public protocol KeyProtectionProvider: Sendable {
    /// Wrap a raw 32-byte seed.  Return nil on failure (registration fails
    /// closed — the engine refuses to persist an unprotected identity).
    func protect(rawSeed: [UInt8]) -> ProtectedKeyMaterial?
    /// Unwrap previously protected material back to the 32-byte seed.
    func unprotect(material: ProtectedKeyMaterial) -> [UInt8]?
}

/// Process-wide registration point.  Install exactly once, before the first
/// EngineController is created.
public enum KeyProtectionRegistry {
    private static let lock = NSLock()
    // The provider is intentionally never cleared while the process lives:
    // the native layer may need `unprotect` at any later engine creation.
    private static var provider: KeyProtectionProvider?

    /// Currently installed provider (used by the C trampolines).
    static func currentProvider() -> KeyProtectionProvider? {
        lock.lock()
        defer { lock.unlock() }
        return provider
    }

    /// Install the platform provider and register the native delegate.
    /// Throws `.internalFailure` when native registration is rejected.
    public static func install(_ newProvider: KeyProtectionProvider) throws {
        lock.lock()
        provider = newProvider
        lock.unlock()

        let status = caelus_mobile_register_key_protection_v1(
            protectTrampoline, unprotectTrampoline, nil)
        guard status == CaelusStatusCode.ok.rawValue else {
            lock.lock()
            provider = nil
            lock.unlock()
            throw CaelusMobileError(
                status: status, detail: "key protection registration rejected")
        }
    }

    public static var isInstalled: Bool { currentProvider() != nil }
}

// MARK: - C trampolines
//
// @convention(c) closures cannot capture state, so they route through the
// registry.  Both directions copy bounded buffers and validate lengths on
// each side of the boundary.

private let protectTrampoline: @convention(c) (
    UnsafeMutableRawPointer?,
    UnsafePointer<CaelusMobileKeyBlob>?,
    UnsafeMutablePointer<CaelusMobileKeyBlob>?
) -> UInt8 = { _, plaintext, protectedOut in
    guard let plaintext, let protectedOut,
          let provider = KeyProtectionRegistry.currentProvider() else {
        return 0
    }
    let input = plaintext.pointee
    guard let inputData = input.data, input.len == 32,
          input.format == KeyBlobFormat.rawSeed else {
        return 0
    }
    let seed = Array(UnsafeBufferPointer(start: inputData, count: input.len))
    guard let wrapped = provider.protect(rawSeed: seed),
          !wrapped.bytes.isEmpty else {
        return 0
    }
    var output = protectedOut.pointee
    guard let outputData = output.data,
          wrapped.bytes.count <= output.capacity else {
        return 0
    }
    wrapped.bytes.withUnsafeBufferPointer { source in
        outputData.update(from: source.baseAddress!, count: source.count)
    }
    output.len = wrapped.bytes.count
    output.format = wrapped.format
    protectedOut.pointee = output
    return 1
}

private let unprotectTrampoline: @convention(c) (
    UnsafeMutableRawPointer?,
    UnsafePointer<CaelusMobileKeyBlob>?,
    UnsafeMutablePointer<CaelusMobileKeyBlob>?
) -> UInt8 = { _, protectedIn, plaintextOut in
    guard let protectedIn, let plaintextOut,
          let provider = KeyProtectionRegistry.currentProvider() else {
        return 0
    }
    let input = protectedIn.pointee
    guard let inputData = input.data, input.len > 0 else { return 0 }
    let material = ProtectedKeyMaterial(
        bytes: Array(UnsafeBufferPointer(start: inputData, count: input.len)),
        format: input.format)
    guard let seed = provider.unprotect(material: material),
          seed.count == 32 else {
        return 0
    }
    var output = plaintextOut.pointee
    guard let outputData = output.data, output.capacity >= 32 else { return 0 }
    seed.withUnsafeBufferPointer { source in
        outputData.update(from: source.baseAddress!, count: source.count)
    }
    output.len = 32
    output.format = KeyBlobFormat.rawSeed
    plaintextOut.pointee = output
    return 1
}
